### ISSUE TITLE
joinx release miss the build-common directory content

### ISSUE THREAD

**Issue by EricDeveaud** [genome/joinx#7]
Hi, 

for production us we only install "releases" (we need to be abble to rebuild exactly the same tools at any moment)
trying to install joinx-1.10.1 (https://github.com/genome/joinx/archive/v1.10.1.tar.gz)
we found that the corresponding archive miss the build common directory content, so render it impossible buildable from stock.
also are the previous release to.

any reason that build-common is not included in the release ?

best regards

Eric

PS I have read the issue #5

**Comment by ernfrid** [comment]
Hi Eric,

This is due to how github bundles release archives. Submodules are not included in the archives and thus, like in issue #5 the submodule is missing. If you are interested in building the releases you should be able to clone them directly from the repository by release name, using the --recursive option, and proceed.

For example, in more recent versions of git you should be able to use: `git clone --branch v1.10.1 --recursive https://github.com/genome/joinx.git`

**Comment by tabbott** [comment]
Hi Eric,

I just pushed a commit that uses build-common as a git subtree rather than a git submodule. Downloading release tar files should now work, but building directly from a git repository is the preferred method.

**Comment by EricDeveaud** [comment]
thanks for that.

sorry for the long delay in replying.

best
Eric
